---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(shiny)
library(wordcloud)
library(tidytext)
library(tm)
library(gridExtra)
library(gridGraphics)
library(ggwordcloud)
library(tm)
library(reshape2)
library(ggplot2)
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
# import data 
kickstarter <- read.csv("kickstarter_2020.csv")
# wrangle
text <- kickstarter %>%
  select(blurb, name, outcome, main_category)


small_data <- kickstarter %>%
  select(blurb, name)

# remove stop words 
data(stop_words)
wordcloud_data <- text %>%
   unnest_tokens(output = word, input = blurb) %>%
   anti_join(stop_words, by = "word")

title_data <- text %>% 
  unnest_tokens(output = word, input = name, drop = FALSE) %>%
  anti_join(stop_words, by = "word")
  
new_text <- inner_join(wordcloud_data, small_data, by = "name")
```

```{r}
# side by side word cloud
par(mfrow=c(1,2), xpd=NA)
# creating wordcloud for successful
set.seed(189) # reproducible randomness
successful_text <- new_text %>%
    filter(main_category == "Technology") %>%
    filter(outcome == "successful")
  
wordcloud(words = successful_text$word, max.words = 40, colors = c("lightsteelblue1","lightsteelblue2","lightsteelblue3","lightsteelblue"))

# creating wordcloud for failed 
failed_text <- new_text %>%
    filter(main_category == "Technology") %>%
    filter(outcome == "failed") 
wordcloud(words = failed_text$word, max.words = 30, color = c("indianred1","indianred2","indianred3","indianred"))

```


```{r word comparison cloud}
# WORKING COMPARISON CLOUD!!!!!!!
tech <- new_text %>% 
  filter(main_category == "Technology")

art <- new_text %>% 
  filter(main_category == "Art")

food <- new_text %>% 
  filter(main_category == "Food")

fashion <-  new_text %>% 
  filter(main_category == "Fashion")

comics <- new_text %>% 
  filter(main_category == "Comics")


tech %>% 
  count(word, outcome, sort = T) %>% 
  acast(word ~outcome, value.var = "n", fill = 0) %>% 
  comparison.cloud(colors = c("blue", "red"), max.words = 100)


food %>% 
  count(word, outcome, sort = T) %>% 
  acast(word ~ outcome, value.var = "n", fill = 0) %>% 
  comparison.cloud(colors = c("red", "blue"), max.words = 100)

fashion %>% 
  count(word, outcome, sort = T) %>% 
  acast(word ~ outcome, value.var = "n", fill = 0) %>% 
  comparison.cloud(colors = c("red", "blue"), max.words = 100)

comics %>% 
  count(word, outcome, sort = T) %>% 
  acast(word ~ outcome, value.var = "n", fill = 0) %>% 
  comparison.cloud(colors = c("#ed4752", "#05ce78"), max.words = 100)


```



# Sentiment Analysis - Blurb

```{r bing lexicon}
# using bing lexicon (pos or neg)
bing <- get_sentiments("bing")

blurb_sentiment <- new_text %>% 
  inner_join(bing) %>% 
  mutate(blurb_length = nchar(blurb))

blurb_sentiment %>% filter(name == "_DarkNet")


# creating sentiment score
tt_bing <- blurb_sentiment %>% 
  group_by(name, outcome) %>% 
  summarize(sentiment_score = sum(sentiment == "positive") - sum(sentiment == "negative"),
            tPos = sum(sentiment == "positive"), tNeg = sum(sentiment == "negative"))

bing_tbl <- tt_bing %>% 
  group_by(outcome) %>% 
  summarise(mean_sent_score = mean(sentiment_score),
            sd = sd(sentiment_score),
            median = median(sentiment_score))

# sentiment score faceted plot
ggplot(data = tt_bing, aes(x = sentiment_score, fill = outcome)) + 
  geom_histogram(bins = 15) +
  facet_grid(~outcome) + 
  labs(title = "Sentiment Score by Outcome - Bing Lexicon", x = "Sentiment Score (Bing lexicon)") + 
  scale_fill_manual(values = c("#ed4752", "#05ce78")) +
  theme_bw() +
  theme(legend.position = "none") 
```


```{r afinn lexicon}
# using afinn lexicon
afinn <- get_sentiments("afinn")

blurb_sentiment_fin <- new_text %>% 
  inner_join(afinn) %>% 
  mutate(blurb_length = nchar(blurb))


# created sentiment score!!!!
tt_afinn <- blurb_sentiment_fin %>% 
  group_by(name, outcome) %>% 
  summarize(sentiment_score = sum(value))

afinn_tbl <- tt_afinn %>% 
  group_by(outcome) %>% 
  summarise(mean_sent_score = mean(sentiment_score),
            sd = sd(sentiment_score),
            median = median(sentiment_score))


# sentiment score faceted plot
ggplot(data = tt_afinn, aes(x = sentiment_score, fill = outcome)) + 
  geom_histogram(bins = 15) +
  facet_grid(~outcome) + 
  labs(title = "Sentiment Score by Outcome - Afinn Lexicon", x = "Sentiment Score (Afinn lexicon)") + 
  scale_fill_manual(values = c("#ed4752", "#05ce78")) +
  theme_bw() +
  theme(legend.position = "none") 

# boxplot
ggplot(tt_afinn) + geom_boxplot(aes(x = sentiment_score, y = outcome))
```


# Name Sentiment Analysis

```{r}
name_sentiment_fin <- title_data %>% 
  inner_join(afinn)

# sentiment score
name_afinn_scores <- name_sentiment_fin %>% 
  group_by(name, outcome) %>% 
  summarize(sentiment_score = sum(value))

# sentiment score faceted plot
ggplot(data = name_afinn_scores, aes(x = sentiment_score, fill = outcome)) + 
  geom_histogram(bins = 15) +
  facet_grid(~outcome) + 
  labs(title = "Sentiment Score by Outcome - Afinn Lexicon", x = "Sentiment Score (Afinn lexicon)") + 
  scale_fill_manual(values = c("#ed4752", "#05ce78")) +
  theme_bw() +
  theme(legend.position = "none") 

# boxplot
ggplot(name_afinn_scores) + geom_boxplot(aes(x = sentiment_score, y = outcome))
```




```{r}
binary_afinn <- tt_afinn %>% 
  mutate(outcome = ifelse(outcome == "successful", 1, 0))
# logit model - not great
library(pscl) # for McFadden R^2
install.packages("pscl")
pR2(model)
logit <- glm(formula = outcome ~ sentiment_score, data = binary_afinn, family = "binomial")
summary(logit)
pR2(logit)
```






```{r length}
# blurb length by outcome
length_data <- text %>% 
  mutate (blurb_length = nchar(blurb),
          name_length = nchar(name))
length_summary <- length_data %>% 
  group_by(outcome) %>% 
  summarise(mean_blurb_length = mean(blurb_length), n = n(),
            mean_name_length = round(mean(name_length), 1)) %>% 
  mutate(mean_blurb_length = round(mean_blurb_length, 1),
         outcome = as.factor(outcome))
# reorder levels of outcome factor
length_summary$outcome <- factor(length_summary$outcome, levels=rev(levels(length_summary$outcome)))

# blurb length plot
ggplot(length_summary, aes(x = mean_blurb_length, y = outcome)) + 
  geom_bar(stat = "identity", aes(fill = outcome)) +
  theme_minimal() + labs(x = "Mean Blurb Length (characters)", y = "Outcome", title = "Blurb Length by Outcome") + 
  geom_label(aes(label = mean_blurb_length)) +
  scale_fill_manual(values=c("#05ce78", "#ed4752")) +
  theme(legend.position = "none")


# name length plot
ggplot(length_summary, aes(x = mean_name_length, y = outcome)) + 
  geom_bar(stat = "identity", aes(fill = outcome)) +
  theme_minimal() + labs(x = "Mean Name Length (characters)", y = "Outcome", title = "Name Length by Outcome") + 
  geom_label(aes(label = mean_name_length)) +
  scale_fill_manual(values=c("#05ce78", "#ed4752")) +
  theme(legend.position = "none")

```









```{r eval = F}
# comparison cloud - failed attempt

dfAll <- new_text %>%
    filter(main_category == "Technology") 
docAll <- dfAll$word

df1 <- new_text %>%
    filter(main_category == "Technology") %>%
    filter(outcome == "successful")
doc1 <- df1$word

df2 <- new_text %>%
    filter(main_category == "Technology") %>%
    filter(outcome == "failed")
doc2 <- df2$word

corpus_all <- 

my_corpus <- VCorpus(VectorSource(doc1))
my_corpus2 <- VCorpus(VectorSource(doc2))

tdm <- TermDocumentMatrix(my_corpus)


c<- VCorpus(VectorSource(kickstarter$blurb))
data =tm_map(c, removeWords, stopwords("english"))
TermDocumentMatrix(data)

```





